name: Deploy to Fly.io
on:
  push:
    branches: [ "main", "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Set app secrets on Fly
        run: flyctl secrets set BOT_TOKEN=${{ secrets.BOT_TOKEN }} --app den4ik --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy
        run: flyctl deploy --remote-only --app den4ik
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
